 <section>
    <div class="container">

    <?php if(ADS_DISPLAY): ?>
      <div class="center topadholder">
    <script type="text/javascript"><!--
    google_ad_client = "ca-pub-4671233287624807";
    /* LS 3.0 Home Skyscraper */
    google_ad_slot = "2426392461";
    google_ad_width = 728;
    google_ad_height = 90;
    //-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
  </div>
  <?php endif; ?>
    <div class="row">  

<div class="span8">
  <div style="display: table">
  <div class="promo" style="width: 620px; height: 300px; display: table-cell; vertical-align: middle; line-height: 1.1em; font-size: 1.4em; font-weight: bold; color: white; text-shadow: 0px 0px 5px rgba(0,0,0,.8); background: rgba(0,0,0,.8) url('/img/gamewall.jpg'); " >
    <div class="text" style="display: table-cell; vertical-align: bottom; padding: 30px; background: -moz-linear-gradient(top, rgba(0,0,0,0) 0%, rgba(0,0,0,0.65) 73%, rgba(0,0,0,0.65) 99%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(73%,rgba(0,0,0,0.65)), color-stop(99%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top, rgba(0,0,0,0) 0%,rgba(0,0,0,0.65) 73%,rgba(0,0,0,0.65) 99%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top, rgba(0,0,0,0) 0%,rgba(0,0,0,0.65) 73%,rgba(0,0,0,0.65) 99%); /* Opera 11.10+ */
background: -ms-linear-gradient(top, rgba(0,0,0,0) 0%,rgba(0,0,0,0.65) 73%,rgba(0,0,0,0.65) 99%); /* IE10+ */
background: linear-gradient(to bottom, rgba(0,0,0,0) 0%,rgba(0,0,0,0.65) 73%,rgba(0,0,0,0.65) 99%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00000000', endColorstr='#a6000000',GradientType=0 ); /* IE6-9 */ height: 300px;">
    <h3>Tus juegos favoritos en un solo lugar</h3>
          <p>
        El primer portal de compra-venta dedicado exclusivamente a los videojuegos se renueva para que puedas sacarle todo el jugo a tu consola. Publicá tus juegos gratis y vendelos o cambialos por el que estás buscando. ¿Qué esperás?
      </p>
</div>
      </div>
    </div>
      <hr class="dark"/>
  <div class="row-fluid gamelisting">
        <?php $count = 0; ?>
        <?php foreach($this->game_list as $game): ?>
        <?php if($count == 2): ?>
          <?php $count = 0; ?>
          </div>
          <div class="row-fluid gamelisting">
          <?php endif; ?>

        <?php $count++; ?>
          <div class="span6">
            <div class="gamecontainer">
              <div class="boxart">
                <a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">
                 <?php echo $this->renderImage('boxart100', $game->getBoxArt(), array()); ?>   
              </a>
              </div>
              <div class="text">
                <p class="platform"><small><?php echo $game->getPlatformInfo()->name; ?></small></p>
                <h4>
<a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">
                  <?php echo $game->name; ?>
</a>
                </h4>
                <div class="cycle">
                <?php if($game->hasSaleOption()): ?>
                  <p class="price">
                    <a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">
                      Compralo desde $<?php echo $game->getLowerPrice(); ?></a></p>
                <?php endif; ?>
                <?php if($game->hasExchangeOption()): ?>
                  <p class="price"><a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">Cambialo gratis!</a></p>
                <?php endif; ?> 
                </div>

                <div class="icons">
                  <span class="showtooltip" title="<?php echo count($game->getInterestedUsers()); ?> usuarios agregaron <?php echo $game->name; ?> a sus favoritos">
                  <i class="icon icon-heart"></i> <?php echo count($game->getInterestedUsers()); ?>
                </span> <span class="splitter">|</span>
                <span class="showtooltip" title="<?php echo count($game->getOwners()); ?> usuarios tienen y juegan <?php echo $game->name; ?>">
                  <i class="icon icon-tags"></i> <?php echo count($game->getOwners()); ?>
                </span> 

                <?php if(count($game->getUserRatings())): ?>
                <span class="splitter">|</span> <span class="showtooltip" title="Puntaje otorgado por usuarios">
                  <i class="icon icon-star"></i> <?php echo $game->getUserRating(); ?>
                </span>
              <?php endif; ?>
                </div>


              </div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
  
    </div>

    <script type="text/javascript">
    $(function() {
      $('.cycle').each(function() {
        $(this).cycle({ 
    fx:      'scrollHorz',
    easeIn:  'easeOutBounce', 
});
      });
    });
      
    </script>


      <div class="span4">

    <h3>Renová tu juegoteca</h3>
        <p>LaSuricata es tu lugar para publicar tus juegos y venderlos o cambiarlos. <b>Es fácil y gratis.</b></p>
    <a href="<?php echo $this->url(array(), 'publishGame'); ?>">
        <div class="box">

      <div class="text">
        <h3><i class="icon icon-2x icon-plus-sign"></i> Publicá tus juegos</h3>
      </div>
    
      
    </div>
    </a>
    <hr>

    <?php $users = $this->picture_users; ?>

    <h3>Directorio de Jugadores</h3>
        <p>Formá parte de nuestra comunidad registrando tu Gamertag o PSN ID y enfrentate a nuevos rivales.  </p>

    <div class="row-fluid">
      <?php $count = 0; ?>
      <?php foreach($users as $user): ?>
        <?php $count++; ?>
        <div class="span2">
          <div class="playerbox" title="<?php echo $user->username; ?> <?php echo ($user->psn_id!='')?'(PSN: '.$user->psn_id.')':''; ?> <?php echo ($user->live_gamertag!='')?'(GT: '.$user->live_gamertag.')':''; ?>">
                      <?php echo $this->renderImage('profilehome', $user->getProfilePic(), array()); ?>
          </div>
        </div>

        <?php if($count == 6): ?>
        </div>
        <div class="row-fluid">
        <?php $count = 0; ?>
        <?php endif; ?>

      <?php endforeach; ?>

      <div class="baloontip_container">
            <div class="baloontip_arrow"></div>
            <div class="baloontip_text">
              Todavía no registraste tu <b>GAMERTAG</b> o <b>PSN ID</b>? <b>Qué esperas?
              <a href="<?php echo $this->url(array(), 'registerProfile'); ?>">Hacelo ya mismo!</a></b>
            </div>
          </div>


    </div>
<hr class="dark" />
<?php if(ADS_DISPLAY): ?>
    <div class="">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-4671233287624807";
/* LS 3.0 Home Side */
google_ad_slot = "9332380460";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<?php endif;?>
      <!--h3>Agenda de eventos</h3>
               <p>
      Sumate a campeonatos, competencias o desafíos con jugadores de la comunidad. Organizá tus propios eventos y encontrá nuevos adversarios.
      </p>

      <div class="boxbig">
        <img src="http://lh3.ggpht.com/_RU8vXW4WLqU/TQTkY83bvDI/AAAAAAAAYC4/rET7pGvcGZQ/Forza%20Motorsport%204%20logo.jpg" />
        <div class="text">
          <p><small>Próximo Evento</small></p>
          <h4>
            Torneo Forza Motorsport 4
          </h4>
          <p>LaSuricata convoca a todos los jugadores de FM4 al primer torneo oficial.
          <h5>29/12/2012</h5>
        </div>
      </div>
  
  <div class="row-fluid">
        <div class="span6">
          <div class="box noicon">
            <div class="text">
              <h4>Copa Navideña 2012</h4>
              <h5>Play x Fun</h5>
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="box"><div class="text">Hola</div></div>
        </div>


      </div>

      <div class="row-fluid">
        <div class="span12">
          <div class="boxhalf">
            <div class="icon">
              <img src="img/icons/calendar.png"  />
            </div>
            <div class="text">
              <h4>Ver todos los eventos</h4>
            </div>  
          </div>
        </div>
      </div-->



    </div>

    

    
    


  </div>  
    </div>
    
  </section>

  <script type="text/javascript">
$(function() {
  $('.playerbox').tooltip();
});
  </script>