
<nav class="filterbar">
	  	<div class="container">
	  		<ul class="filters">
			  <li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			      Plataforma: <b><?php echo ($this->platform_info)?$this->platform_info->name:'Todas'; ?></b>
			      <b class="caret"></b>
			    </a>
			    <ul class="dropdown-menu">
			    	<li><a href="<?php echo $this->url(array('platform_identifier'=>'todas', 'filters'=>$this->filterString(array('page'=>1))->getString())); ?>">Todas</a></li>
			    	<?php foreach($this->platform_list as $platform): ?>
			    		<li><a href="<?php echo $this->url(array('platform_identifier'=>$platform->identifier, 'filters'=>$this->filterString(array('page'=>1))->getString())); ?>"><?php echo $platform->name; ?></a></li>
			    	<?php endforeach; ?>
			    </ul>
			  </li>

			   <li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			      Categoría: <b><?php echo ($this->category_info)?$this->category_info->name:'Todas'; ?></b>
			      <b class="caret"></b>&nbsp;
			    </a>
			    <ul class="dropdown-menu">
<li><a href="<?php echo $this->url(array('category_identifier'=>'todas')); ?>">Todas</a></li>
			    	<?php foreach($this->category_list as $category): ?>
			    		<li><a href="<?php echo $this->url(array('category_identifier'=>$category->identifier, 'filters'=>$this->filterString(array('page'=>1))->getString())); ?>"><?php echo $category->name; ?></a></li>
			    	<?php endforeach; ?>
			    </ul>
			  </li>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Ordenar por: <b><?php echo $this->sortoptions[$this->currentsort]; ?></b>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <?php foreach($this->sortoptions as $key => $display): ?>
              <li><a href="<?php echo $this->url(array('filters'=>$this->filterString(array('order'=>$key,'page'=>1))->getString())); ?>"><?php echo $display; ?></a></li>
            <?php endforeach; ?>
          </ul>
        </li>





			</ul>
	  	</div>
</nav>

<section>
<div class="container">
	<div class="row-fluid">
		<div class="span8">
        <?php echo $this->paginationControl($this->game_list, 'Sliding', 'slices/pagination/product_navbar.phtml'); ?>
<hr class="small" />
  <div class="row-fluid gamelisting">
        <?php $count = 0; ?>
        <?php foreach($this->game_list as $game): ?>
        <?php if($count == 2): ?>
          <?php $count = 0; ?>
          </div>
          <div class="row-fluid gamelisting">
          <?php endif; ?>

        <?php $count++; ?>
          <div class="span6">
            <div class="gamecontainer">
              <div class="boxart">
                <a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">
                 <?php echo $this->renderImage('boxart100', $game->getBoxArt(), array()); ?>   
              </a>
              </div>
              <div class="text">
                <p class="platform"><small><?php echo $game->getPlatformInfo()->name; ?></small></p>
                <h4>
<a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">
                  <?php echo $game->name; ?>
</a>
                </h4>
                <div class="cycle">
                <?php if($game->hasSaleOption()): ?>
                  <p class="price">
                    <a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">
                      Compralo desde $<?php echo $game->getLowerPrice(); ?></a></p>
                <?php endif; ?>
                <?php if($game->hasExchangeOption()): ?>
                  <p class="price"><a href="<?php echo $this->url(array('game_identifier'=>$game->identifier,'platform_identifier'=>$game->getPlatformInfo()->identifier), 'gameDetail'); ?>">Cambialo gratis!</a></p>
                <?php endif; ?> 
                </div>

                <div class="icons">
                  <span class="showtooltip" title="<?php echo count($game->getInterestedUsers()); ?> usuarios agregaron <?php echo $game->name; ?> a sus favoritos">
                  <i class="icon icon-heart"></i> <?php echo count($game->getInterestedUsers()); ?>
                </span> <span class="splitter">|</span>
                <span class="showtooltip" title="<?php echo count($game->getOwners()); ?> usuarios tienen y juegan <?php echo $game->name; ?>">
                  <i class="icon icon-tags"></i> <?php echo count($game->getOwners()); ?>
                </span> 

                <?php if(count($game->getUserRatings())): ?>
                <span class="splitter">|</span> <span class="showtooltip" title="Puntaje otorgado por usuarios">
                  <i class="icon icon-star"></i> <?php echo $game->getUserRating(); ?>
                </span>
              <?php endif; ?>
                </div>


              </div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
      <hr class="small dark"/>
              <?php echo $this->paginationControl($this->game_list, 'Sliding', 'slices/pagination/product_bottom.phtml'); ?>
      </div>
      <div class="span4">
        
        <?php echo $this->partial('slices/widgets/suggestion_side.phtml'); ?>
    <?php if(ADS_DISPLAY): ?>

        <?php if(rand(1,1)): ?>
        <script type="text/javascript"><!--
          google_ad_client = "ca-pub-4671233287624807";
          /* LS 3.0 Search Mediumbox */
          google_ad_slot = "5019932066";
          google_ad_width = 300;
          google_ad_height = 250;
          //-->
          </script>
        <script type="text/javascript"
          src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
      <?php else: ?>
      <script type="text/javascript"><!--
      google_ad_client = "ca-pub-4671233287624807";
      /* LS 3.0 Side Vertical */
      google_ad_slot = "3403598062";
      google_ad_width = 300;
      google_ad_height = 600;
      //-->
      </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
      <?php endif; ?>
    <?php endif; ?>
      </div>


  </div>
  </div>
</section>


  <script type="text/javascript">
    $(function() {
      $('.cycle').each(function() {
        $(this).cycle({ 
    fx:      'scrollHorz',
    easeIn:  'easeOutBounce', 
});
      });
    });
      
    </script>