<!DOCTYPE HTML>
<html lang="es">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# lasuricatacom: http://ogp.me/ns/fb/lasuricatacom#">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <?php echo $this->headTitle(); ?>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php echo $this->openGraph()->render(); ?>
  <?php echo $this->headMeta() ?>
  <?php echo $this->headStyle() ?>
  <?php echo $this->headLink() ?>

  <link href='/css/bootstrap.css' rel='stylesheet' type='text/css'>
  <link href='/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
  <link href='/css/feline.css' rel='stylesheet' type='text/css'>
  <link href='/css/jquery-ui.css' rel='stylesheet' type='text/css'>

  <script src="/js/jquery-1.8.3.js" type="text/javascript"></script>
  <script src="/js/jquery.easing.1.3.js" type="text/javascript"></script>
  <script src="/js/jquery.raty.min.js" type="text/javascript"></script>
  <script src="/js/jquery.cycle.all.js" type="text/javascript"></script>
  <script src="/js/lasuricata.feline.js" type="text/javascript"></script>
  <script src="/js/bootstrap.js" type="text/javascript"></script>
  <script src="/js/jquery.smart-slider.js" type="text/javascript"></script>
  <script src="/js/jquery-ui.min.js" type="text/javascript"></script>
  <script src="/js/jquery.jnotify.min.js" type="text/javascript"></script>
  

<body>
  <header>
    <div class="container">
        <a href="/" class="logo-container" title="Página principal de LaSuricata">
            <img class="logo" src="http://static.lasuricata.com/img/suricata_new.png" alt="Don Suricata"/>
          </a>
          <div class="pull-right form-inline">
          <?php if($this->loginInfo()->status != 9): ?>
                <span class="username"><i class="icon-user"></i> <?php echo $this->loginInfo()->username; ?></span>

                <a title="Ver mensajes" class="btn btn-link headerbutton <?php echo (count($this->loginInfo()->getUnreadMessages())>0)?'highlight':''; ?>" href="<?php echo $this->url(array(), 'profileInbox'); ?>"><i class="icon-envelope"></i> Mensajes (<?php echo count($this->loginInfo()->getUnreadMessages()); ?>)</a>


                <a title="Ver intercambios" class="btn btn-link headerbutton" href="<?php echo $this->url(array(), 'profileExchanges'); ?>"><i class="icon-exchange"></i> Intercambios (<?php echo count($this->loginInfo()->getRequests('status', EVENT_STATUS_SENT)); ?>)</a>

                <a title="Ajustar opciones" class="btn btn-link headerbutton" href="<?php echo $this->url(array(), 'profileSettings'); ?>"><i class="icon icon-cog"></i> Opciones</a>
                <a title="Cerrar sesión" class="btn btn-link headerbutton" href="<?php echo $this->url(array(), 'logOutRedirect'); ?>"><i class="icon icon-signout"></i> Salir</a>
          <?php else: ?>
            <a href="#" class="tokenLink logintext " data-token="<?php echo $this->getToken('login'); ?>">
              <i class="icon icon-signin"></i> 
              Ingresar
            </a>
          <div class="btn-group">
            <a href="<?php echo $this->url(array(), 'registerMain'); ?>" class="btn btn-small btn-warning">
              Crear cuenta
            </a>
          </div>

          <?php endif; ?>

          </div>
    </div>
  </header>
  <nav>
  	<div class="container">
  	<ul class="menu">
  		<li>
  			<a href="<?php echo $this->url(array(), 'index'); ?>" class="<?php echo ($this->isRoute('index'))?'active':''; ?>">Principal</a>
  		</li>
  		<li>
  			<a href="<?php echo $this->url(array(), 'searchGames'); ?>" class="<?php echo ($this->isRoute('searchGames'))?'active':''; ?>">Buscar Juegos</a>
  		</li>
      <li>
        <a href="<?php echo $this->url(array(), 'myGames'); ?>" class="<?php echo ($this->isRoute('myGames'))?'active':''; ?>">Mis Juegos</a>
      </li>
  		<li>
  			<a href="<?php echo $this->url(array(), 'publishGame'); ?>" class="<?php echo ($this->isRoute('publishGame'))?'active':''; ?>">Publicar Juego</a>
  		</li>
  		<li>
  			<a href="<?php echo $this->url(array(), 'playerList'); ?>" class="<?php echo ($this->isRoute('playerList'))?'active':''; ?>">Jugadores</a>
  		</li>

      <?php if(!$this->isRoute('publishRegister')): ?>
      <li class="pull-right">
        <?php if($this->loginInfo()->status == 9 && count($this->loginInfo()->getOwnlist())>0): ?>
        <a href="<?php echo $this->url(array(), 'publishRegister'); ?>">Tenés juegos cargados sin publicar. <b>Activalos ahora!</b></a>
        <?php endif; ?>
      </li>
      <?php endif; ?>
  	</ul>
  	</div>
  </nav>

  <?php if($this->loginInfo()->status == 0): ?>
  <div class="alert alert-warning header">
    <i class="icon icon-warning-sign icon-4x pull-left"></i>
      <h4>Atención</h4>
      Tu dirección de email no ha sido confirmada, por lo que tus juegos no estarán publicados ni podrás interactuar con otros usuarios.<br/>
      Si todavía no recibiste el correo, fijate en las carpetas de <b>Spam</b> o <b>Correo No Deseado</b>
  </div>
<?php endif; ?>
<?php foreach ($this->flashMessenger() as $type => $message): ?>
  <div class="alert alert-<?php echo $type; ?> header">
       <button class="close" data-dismiss="alert">×</button>
      <?php if($type == 'danger' || $type == 'warning'): ?>
        <i class="icon icon-warning-sign icon-3x pull-left"></i>
        <h4>Error</h4>
      <?php endif; ?>
      <?php echo $message; ?>
  </div>
  <?php endforeach; ?>

  <?php echo $this->layout()->content; ?>
  <script type="text/javascript">
  $(function() {
    $('.headerbutton').tooltip({placement: 'bottom'});
  });
  </script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22633340-3']);
  _gaq.push(['_setDomainName', 'lasuricata.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<footer>
  <div class="container">
    <img src="/img/icon-footer.png" /><br/>
    Copyright 2013 LaSuricata.com Todos Los Derechos Reservados<br/>

  <a href="<?php echo $this->url(array(), 'privacyPolicy'); ?>">Políticas de Privacidad</a>  

  </div>
</footer>
</body>
</html>